# A_3: Creating a Sparse Matrix

In [1]:
# Problem Statement: Given data with very few nonzero values, efficiently represent it
# Solution: Create a sparse matrix

In [3]:
# load the library

import numpy as np
from scipy import sparse

In [4]:
# create a matrix

matrix = np.array([[0, 0], 
                  [0, 1], 
                  [3, 0]])

In [5]:
# print the matrix

print(matrix)

[[0 0]
 [0 1]
 [3 0]]


In [6]:
# create compressed sparse row (CSR) matrix

matrix_sparse = sparse.csr_matrix(matrix)

In [7]:
# view the sparse matrix

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:
# create a larger matrix

matrix_large_sparse = np.array([[0, 0, 0, 0, 0, 0, 0], 
                        [0, 1, 0, 0, 0, 0, 0], 
                        [3, 0, 0, 0, 0, 0, 0]])

In [14]:
# create a compressed sparse row (CSR) matrix

matrix_sparse = sparse.csr_matrix(matrix_large)

In [15]:
# view the original matrix

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [16]:
# view the larger sparse matrix

print(matrix_large_sparse)

[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [3 0 0 0 0 0 0]]


In [ ]:
# References: 
# Sparse Matrices