# A_4: Pre-allocating NumPy Arrays

In [1]:
# Problem Statement: To pre-allocate arrays of given size with some value
# Solution: NumPy has functions for generating vectors and matrices of any size using 0's and 1's or any number of your choice

In [2]:
# load the library

import numpy as np

In [3]:
# Generate a vector of shape(1, 5) containing all zeroes

vector = np.zeros(shape = 5)

In [4]:
# view the vector

print(vector)

[0. 0. 0. 0. 0.]


In [7]:
# Generate a vector of shape (1, 5) containing all ones

vector = np.ones(shape = 5)

In [8]:
# view the vector

print(vector)

[1. 1. 1. 1. 1.]


In [9]:
# Generate a vector of shape (3,3) containing all ones

matrix = np.full(shape = (3, 3), fill_value = 1)

In [10]:
# view the matrix

print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
