# A_5: Selecting Elements

In [1]:
# Probelm Statement: To select one or more elements in a vector or matrix
# Solution: NumPy arrays selects elements in vectors and matrices easily

In [2]:
# load the library

import numpy as np

In [3]:
# create a row vector

vector = np.array([1, 2, 3, 4, 5, 6])

In [4]:
# view the vector

print(vector)

[1 2 3 4 5 6]


In [5]:
# create a matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [6]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# select the third element of vector

vector[2]

3

In [8]:
# select second row, second column of matrix

matrix[1, 1]

5

In [9]:
# select all elements of a vector

vector[:]

array([1, 2, 3, 4, 5, 6])

In [10]:
# select everything upto and including the third element

vector[:3]

array([1, 2, 3])

In [11]:
# select everything after the third element

vector[3:]

array([4, 5, 6])

In [12]:
# select the last element

vector[-1]

6

In [13]:
# reverse the vector

vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [14]:
# select the first row and all columns of a matrix

matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# select all rows and the second column

matrix[:, 1:2]

array([[2],
       [5],
       [8]])