# A_6: Describing a Matrix

In [1]:
# Problem Statement: To describe the shape, size and dimensions of the matrix
# Solution: Use the shape, size and ndim attributes of a NumPy object

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [4]:
# view the matrix

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# view the number of rows and columns

matrix.shape

(3, 4)

In [6]:
# view the number of elements (rows * columns)

matrix.size

12

In [7]:
# view the number of dimensions

matrix.ndim

2