# A_7: Applying Functions Over Each Element


In [1]:
# Problem Statement: To apply some functions to all elements in an array
# Solution: Use NumPy's vectorize method

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [4]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# create the function that adds 100

add_100 = lambda i: i + 100

In [6]:
# create vectorized function

vec_add_100 = np.vectorize(add_100)

In [7]:
# apply function to all elements in the matrix

vec_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
# References:
# vectorize is a for loop over elements and does not increase performance
# broadcasting --> perform operations between arrays even if dimensions are not the same

In [9]:
# broadcasting

# add 100 to all elements

matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [10]:
# References:
# broadcasting doesnot work for all shapes
# applying simple operations over all elements of a numpy array
