# A_8: Finding the Maximum and the Minimum Values

In [1]:
# Problem Statement: To find the maximum and the minimum values in an array
# Solution: Use NumPy's max and min method

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [4]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# return the maximum element

np.max(matrix)

9

In [6]:
# return the minimum element

np.min(matrix)

1

In [7]:
# Using the axis parameter

In [8]:
# find the maximum element in each column

np.max(matrix, axis = 0)

array([7, 8, 9])

In [9]:
# find the maximum element in each row

np.max(matrix, axis = 1)

array([3, 6, 9])