# A__12: Flattening a Matrix

In [1]:
# Problem Statement: To transform a matrix into a one-dimensional array
# Solution: Use flatten

In [2]:
# load the library

import numpy as np

In [4]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [5]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# flatten the matrix

matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# flatten --> method to transform a matrix into one-dimensional array
# alternatively, reshape to craete a row vector

In [8]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
# Method 2: ravel --> operates on a original object itself and is faster
# useful for large array and speeding up

In [13]:
# create the first matrix

matrix_a = np.array([[1, 2], 
                    [3, 4]])

In [14]:
# view the first matrix

print(matrix_a)

[[1 2]
 [3 4]]


In [15]:
# create a second matrix

matrix_b = np.array([[5, 6], 
                    [7, 8]])

In [16]:
# view the second matrix

print(matrix_b)

[[5 6]
 [7 8]]


In [17]:
# create a list of matrices

matrix_list = [matrix_a, matrix_b]

In [18]:
# view the list of matrices

print(matrix_list)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [19]:
# flatten the matrix list

np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])