# A__10: Reshaping Arrays

In [2]:
# Problem Statement: To change the shape (number of rows and columns) in an array without changing the element values
# Solution: Use NumPy's reshape

In [3]:
# load the library

import numpy as np

In [4]:
# create a 4x3 matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9], 
                  [10, 11, 12]])

In [5]:
# view the matrix

print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# reshape the matrix into 2x6 matrix

matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
# reshape --> restructure the array
# maintain same data, but different number of rows and columns

In [8]:
# size of matrix

matrix.size

12

In [10]:
# argument in reshape, -1 --> as many as needed
# reshape(1, -1) --> one row and as many columns

matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [11]:
# for one integer reshape returns 1D array of that length

matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])