# A__11: Transposing a Vector or Matrix

In [1]:
# Problem Statement: To transpose a vector or matrix
# Solution: Use T method

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]])

In [4]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# transpose the matrix

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
# transposing --> common operation in linear algebrsa
# column and row indices of each element are swapped

In [14]:
# vector cannot be transposed, as it is a collection of values

# transpose a vector

np.array([1, 2, 3, 4, 5, 6]). T

array([1, 2, 3, 4, 5, 6])

In [15]:
# transposing, converting row vector to column vector or vice versa

# transpose a row vector

np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])