# A__14: Getting the Diagonal of a Matrix

In [1]:
# Problem Statement: To get the diagonal elements of a matrix
# Solution: Use diagonal

In [2]:
# load the library

import numpy as np

In [4]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [5]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# return diagonal elements

matrix.diagonal()

array([1, 5, 9])

In [7]:
# To diagonal off from the main diagonal use the offset parameter

In [8]:
# return diagonal one above the main diagonal

matrix.diagonal(offset = 1)

array([2, 6])

In [9]:
# return the diagonal one below the main diagonal

matrix.diagonal(offset = -1)

array([4, 8])