# A__17: Adding and Subtracting Matrices 

In [1]:
# Problem Statement: To add or subtract two matices
# Solution: Use NumPy's add and subtract

In [2]:
# load the library

import numpy as np

In [13]:
# create the first matrix

matrix_a = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

In [14]:
# view the first matrix

print(matrix_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# create the second matrix

matrix_b = np.array([[1, 3, 1], 
                    [1, 2, 1], 
                     [1, 3, 8]])

In [16]:
# view the second matrix

print(matrix_b)

[[1 3 1]
 [1 2 1]
 [1 3 8]]


In [17]:
# add the two matrices

np.add(matrix_a, matrix_b)

array([[ 2,  5,  4],
       [ 5,  7,  7],
       [ 8, 11, 17]])

In [18]:
# subtract the two matrices

np.subtract(matrix_a, matrix_b)

array([[ 0, -1,  2],
       [ 3,  3,  5],
       [ 6,  5,  1]])