# A__18: Multiplying Matrices 

In [1]:
# Problem Statement: To multiply two matrices
# Solution: Use NumPy's dot

In [2]:
# load the library

import numpy as np

In [3]:
# create the first matrix

matrix_a = np.array([[1, 1], 
                    [1, 2]])

In [4]:
# view the first matrix

print(matrix_a)

[[1 1]
 [1 2]]


In [5]:
# create the second matrix

matrix_b = np.array([[3, 4], 
                    [5, 6]])

In [7]:
# view the second matrix

print(matrix_b)

[[3 4]
 [5 6]]


In [8]:
# multiply two matrices

np.dot(matrix_a, matrix_b)

array([[ 8, 10],
       [13, 16]])

In [9]:
# Alternatively, use the @ operator

matrix_a @ matrix_b

array([[ 8, 10],
       [13, 16]])

In [10]:
# to do element-wise multiplication, use * operator

matrix_a * matrix_b

array([[ 3,  4],
       [ 5, 12]])

In [11]:
# References:
# Array Vs. Matrix Operations, MathWorks