# A__19: Inverting a Matrix

In [1]:
# Problem Statement: To calculate the inverse of a square matrix
# Solution: Use NumPy's linear algebra inv method

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 4], 
                  [2, 5]])

In [4]:
# view the matrix

print(matrix)

[[1 4]
 [2 5]]


In [5]:
# calculate the inverse of matrix

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [8]:
# multiply matrix and its inverse

matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [9]:
# References:
# Inverse of a Matrix