# A__15: Calculating the Trace of a Matrix

In [1]:
# Problem Statement: To calculate the trace of a matrix
# Solution: Use trace

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [4]:
# view the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# return the trace

matrix.trace()

15

In [8]:
# Trace of the matrix is the sum of the diagonal elements
# Also, return the diagonal of a matrix and calculate its sum

In [9]:
# return the diagonal and sum elements

sum(matrix.diagonal())

15

In [10]:
# References: The Trace of a Square Matrix