# A__13: Finding the Rank of a Matrix 

In [1]:
# Problem Statement: To know the rank of a matrix
# Solution: Use NumPy's linear algebra method matrix_rank

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 1, 1], 
                  [1, 1, 10], 
                  [1, 1, 15]])

In [4]:
# view the matrix

print(matrix)

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


In [5]:
# return the matrix rank

np.linalg.matrix_rank(matrix)

2

In [6]:
# References:
# The rank of matrix is the dimensions of the vector space spanned by its columns or rows