# A__20: Generating Random Values

In [1]:
# Problem Statement: To generate pseudorandom numbers
# Solution: Use NumPy's random

In [2]:
# load the library

import numpy as np

In [3]:
# set seed

np.random.seed(0)

In [4]:
# generate three random floats between 0.0 and 1.0

np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [5]:
# common to generate intergers, other than floats

In [6]:
# generate three random numbers between 0 and 10

np.random.randint(0, 11, 3)

array([3, 7, 9])

In [7]:
# generate numbers from drawing them from a distribution

In [8]:
# draw three numbers from a normal distribution with mean 0.0 and standard deviation 1.0

np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [9]:
# draw three numbers from a logistic distribution with mean 0.0 and standard deviation 1.0

np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [10]:
# draw three numbers greater than or equal to 1.0 and less than 2.0

np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])