# A4: Pre-allocating Numpy Arrays

In [1]:
# Problem Statement: to pre-allocate arrays of a given size with some value
# Solution: numPy has functions for generating vctors and matrices of any size using 0's and 1's 

In [2]:
# Load the library

import numpy as np

In [4]:
# generate a vector of shape(1, 5) containing all zeroes

vector = np.zeros(shape = 5)

In [5]:
# print the vector

print(vector)

[0. 0. 0. 0. 0.]


In [7]:
# generate a matrix of shape(3, 3) containing all ones

matrix = np.full(shape = (3, 3), fill_value = 1)

In [8]:
# print the vector\

print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
