# A5: Selecting Elements

In [1]:
# Problem Statement: to select one or more elements in a vector or matrix
# Solution: Use numPy's arrays to select elements in vectors or matrices

In [2]:
# Load the library

import numpy as np

In [3]:
# create a row vector

vector = np.array([1, 2, 3, 4, 5, 6])

In [8]:
# print the vector

print(vector)

[1 2 3 4 5 6]


In [9]:
# select the third element of vector\

vector[2]

3

In [10]:
# create matrix

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [11]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# select the second row, second column

matrix[1, 1]

5

In [12]:
# select all elements of a vector

vector[:]

array([1, 2, 3, 4, 5, 6])

In [13]:
# select everything upto and including the third element

vector[:3]

array([1, 2, 3])

In [14]:
# select everything after the third element

vector[3:]

array([4, 5, 6])

In [15]:
# select the last element

vector[-1]

6

In [16]:
# reverse the vector

vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [17]:
# select the first two rows and columns of a matrix

matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# select all rows and the second column

matrix[:, 1: 2]

array([[2],
       [5],
       [8]])