# A6: Describing a Matrix

In [1]:
# Problem Statement: to describe the shape, size and dimension of the marix
# Solution: Use shape, size and ndim attributes of numPy

In [2]:
# Load the library

import numpy as np

In [6]:
# create the matrix

matrix = np.array([[1, 2, 3, 4],
                  [4, 5, 6, 7],
                  [7, 8, 9, 10]])

In [7]:
# print the matrix

print(matrix)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [8]:
# view the number of rows and columns

matrix.shape

(3, 4)

In [9]:
# view the number of elements (rows * columns)

matrix.size

12

In [10]:
# view the number of dimensions

matrix.ndim

2