# A7: Applying Functions Over Each Element

In [1]:
# Problem Statement: Apply some functions to all elements in an array\
# Solution: Use numPy's vectorize method

In [2]:
# Load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])

In [4]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# create a function that adds 100

add = lambda i: i + 100

In [7]:
# create vectorized function

vec_100 = np.vectorize(add)

In [8]:
# apply function to all elements in matrix

vec_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [9]:
# Broadcasting
# add 100 to all elements

matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])