# A9: Calculating the Average, Variance and Standard Deviation

In [1]:
# Problem Statement: to calculate descriptive statistics of an array
# Solution: Use numPy's mean, var and std

In [2]:
# Load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]])

In [4]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# return matrix

np.mean(matrix)

5.0

In [6]:
# return variance

np.var(matrix)

6.666666666666667

In [7]:
# return standard deviation

np.std(matrix)

2.581988897471611

In [9]:
# perform calculations along a single axis
# find the mean value in each column

np.mean(matrix, axis = 0)

array([4., 5., 6.])