# A14: Getting the Diagonal of a Matrix

In [1]:
# Problem Statement: to get the diagonal elements of a matrix
# Solution: use diagonal

In [2]:
# load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6],
                  [6, 7, 8]])

In [4]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [5]:
# reurn the diagonal elements

matrix.diagonal()

array([1, 5, 8])

In [6]:
# possible to diagonal off from the main diagonal using the offset parameter

In [8]:
# return the diagonal one above the main diagonal

matrix.diagonal(offset = 1)

array([2, 6])

In [9]:
# return the diagonal one below the main diagonal

matrix.diagonal(offset = -1)

array([4, 7])