# A12: Flattening a Matrix

In [1]:
# Problem Statement: to transform a matrix into a one-dimensional array
# Solution: Use flatten

In [2]:
# Load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 2, 3],
                  [5, 6, 7],
                  [6, 7, 8]])

In [4]:
# flatten the matrix

matrix.flatten()

array([1, 2, 3, 5, 6, 7, 6, 7, 8])

In [5]:
# alternatively, reshape to create a row vector

matrix.reshape(1, -1)

array([[1, 2, 3, 5, 6, 7, 6, 7, 8]])

In [6]:
# method 2 - ravel returns a copy of the original array
# ravel operates on the original object itself 
# flatten of arrays

In [7]:
# create matrix A

matrix_A = np.array([[1, 2],
                    [3, 4]])

In [8]:
# print matrix A

print(matrix_A)

[[1 2]
 [3 4]]


In [9]:
# create matrix B

matrix_B = np.array([[5, 6],
                    [7, 8]])

In [10]:
# print matrix B

print(matrix_B)

[[5 6]
 [7 8]]


In [11]:
# create a list of matrices

matrix_list = [matrix_A, matrix_A]

In [12]:
# print the matrix list

print(matrix_list)

[array([[1, 2],
       [3, 4]]), array([[1, 2],
       [3, 4]])]


In [13]:
# flatten the entire list of matrices

np.ravel(matrix_list)

array([1, 2, 3, 4, 1, 2, 3, 4])