# A15: Calculating the Trace of a Matrix

In [1]:
# Problem Statement: To calculate the trace of a matrix
# Solution: Use trace

In [2]:
# Load the library

import numpy as np

In [3]:
# create a martix

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                   [7, 8, 9]])

In [4]:
# print the matrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# return trace

matrix.trace()

15

In [7]:
# also returns the diagnol and sum elements

sum(matrix.diagonal())

15

In [8]:
# References: The Trace of a Square Matrix