# A18: Multiplying Matrices

In [1]:
# Problem Statement: To multiply two matrices
# Solution: Use numPy's dot

In [2]:
# Load the library

import numpy as np

In [3]:
# create matrix A

matrix_A = np.array([[1, 2], 
                    [1, 3]])

In [4]:
# print matrix A

print(matrix_A)

[[1 2]
 [1 3]]


In [5]:
# create matrix B

matrix_B = np.array([[1, 2], 
                    [1, 5]])

In [6]:
# print matrix B

print(matrix_B)

[[1 2]
 [1 5]]


In [7]:
# multiply the matrices

matrix_C = np.dot(matrix_A, matrix_B)

In [8]:
# print the result, matrix C

print(matrix_C)

[[ 3 12]
 [ 4 17]]


In [9]:
# multiply two matrices using @ operator

matrix_A @ matrix_B

array([[ 3, 12],
       [ 4, 17]])

In [11]:
# multiply two matrices element-wise using * operator

matrix_A * matrix_B

array([[ 1,  4],
       [ 1, 15]])

In [12]:
# References: Array Vs. Matrix Operations, MathWorks