# A13: Finding the Rank of a Matrix

In [1]:
# Problem Statement: to find the rank of a matrix
# Solution: Use numpy's linear algebra method matrix_rank

In [2]:
# Load the library

import numpy as np

In [3]:
# create the matrix

matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])

In [4]:
# print the matrix

print(matrix)

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


In [ ]:
# return the ra