# A10: Reshaping Arrays

In [1]:
# Problem Statement: to change the shape of an array without changing the values
# Solution: Use numPy's reshape

In [2]:
# Load the library

import numpy as np

In [3]:
# create 4 X 3 matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9],
                  [10, 11, 12]])

In [4]:
# print the matrix

print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# reshape matrix into 2 x 6 matrix

matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
# size of matrix using size

matrix.size

12

In [7]:
# argument in reshape, -1 means "as many as needed"
# reshape(1, -1) means one row and as many columns 

matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [8]:
# for one integer, reshape, returns 1D array of that length

matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])