# A11: Transposing a Vector or Matrix

In [1]:
# Problem Statement: to transpose a vector or a matrix
# Solution: Use T method

In [2]:
# Load the library

import numpy as np

In [3]:
# create a matrix

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [6, 7, 8]])

In [4]:
# transpose of a matrix

matrix.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [5]:
# vector cannot be transposed as it is a collection of values

In [6]:
# Transpose vector

np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [7]:
# Transposing a vector --> converting  a row vector to a column vector

In [8]:
# Transpose row vector

np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])