# A17: Adding and Subtracting Matrices

In [1]:
# Problem Statement: To add or subtract two matrices
# Solution: Use numPy's add and subtract

In [2]:
# Load the library

import numpy as np

In [4]:
# create the matrix A

matrix_A = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

In [5]:
# create matrix B

matrix_B = np.array([[1, 3, 1], 
                    [1, 3, 1],
                    [1, 3, 8]])

In [7]:
# Add two matrices

matrix_Add = np.add(matrix_A, matrix_B)

In [12]:
# print the result of adding two matrices

print(matrix_Add)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [13]:
# Subtract two matrices

matrix_Sub =np.subtract(matrix_A, matrix_B)

In [15]:
# print the result of subtracting two matrices

print(matrix_Sub)

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [16]:
# + and - operators can also be used

In [17]:
matrix_A + matrix_B

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [18]:
matrix_A - matrix_B

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])