# A20: Generating Random Values

In [ ]:
# Probelm Statement: to generate pseudorandom values
# Solution: Use numPy's random

In [1]:
# Load the library

import numpy as np

In [3]:
# Set seed

np.random.seed(0)

In [4]:
# generate three random floats beteen 0.0 and 1.0

np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [7]:
# to generate integers between 0 and 10

np.random.randint([5, 26, 12])

array([ 0, 24, 10])

In [8]:
# generate numbers from a distribution

In [10]:
# generate three numbers from a normal distribution with mean 0.1, and standard deviation of 1.0

np.random.normal(0.1, 1.0, 3)

array([-0.3530558, -0.370771 ,  1.073016 ])

In [12]:
# generate four numbers from a logistic distribution with mean 0.0 and scale of 1.0

np.random.logistic(0.0, 1.0, 4)

array([ 1.9017305 , -0.10566603,  1.39199631,  0.08195576])

In [13]:
# generate three numbers greater than or equal to 1.0 and less than 2.0

np.random.uniform(1.0, 2.0, 3)

array([1.67887953, 1.72063265, 1.58201979])